package-name: xmc-for-arduino
include:
  - cores
  - libraries
  - tools
  - variants
  - boards.txt
  - platform.txt
  - programmers.txt
  - LICENSE.md
  - README.md
index-name: package_infineon_index
server: 
  type: github
  owner: Infineon
  repo: XMC-for-Arduino