name: Compile examples 0123

on:
  push:
    
jobs:
  compile-examples:
    uses: Infineon/arduino-devops/.github/workflows/compile-examples.yml@compile-example-os-board-matrix
    with:
      ci-matrix-file-json: ci-build-matrix.json 
      os-list: 'ubuntu-latest, windows-latest'
    secrets: inherit