name: Compile examples 123456789012345678901

on:
  push:
    
jobs:
  compile-examples:
    uses: Infineon/arduino-devops/.github/workflows/compile-examples.yml@compile-example-os-board-jobs
    with:
      ci-matrix-file-json: ci-build-matrix.json 
      os-list: 'ubuntu-latest, windows-latest'
    secrets: inherit